Change of the name of the BatchServiceClient class parameter to the one consistent with the documentation. From `base_url` -> (#268)
`batch_url`.
Wrong name caused the error at run time:
```
TypeError: __init__() got an unexpected keyword argument 'base_url'
```